markdown: pandoc
url: 'https://users.soe.ucsc.edu/~ivo'
permalink: pretty
pygments: true
exclude: ['deploy', 'README.md']

pandoc:
  extensions:
    - smart
    - standalone
    - csl: '$HOME/.opt/styles/ieee-w-url.csl'
    - bibliography: '$HOME/.citations/zotero.bib'
    - highlight-style: 'pygments'
