url: 'http://localhost:4000'
permalink: pretty
pygments: true
exclude: ['deploy', 'README.md']
markdown: pandoc

pandoc:
  extensions:
    - smart
    - standalone
    - csl: '$HOME/.opt/styles/ieee-w-url.csl'
    - bibliography: '$HOME/.citations/zotero.bib'
    - highlight-style: 'pygments'
