url: 'http://localhost:4000'
permalink: pretty
pygments: true
exclude: ['deploy', 'README.md']
markdown: pandoc

pandoc:
  flags: "--smart --standalone --csl=$HOME/.opt/styles/ieee-with-url.csl --bibliography=$HOME/.citations/zotero.bib --highlight-style=pygments"
