markdown: pandoc
url: "http://ivotron.me/"
permalink: pretty
pygments: true

pandoc:
  extensions:
    - smart
    - standalone
    - csl: '$HOME/.opt/styles/ieee-w-url.csl'
    - bibliography: '$HOME/.citations/zotero.bib'
    - highlight-style: 'pygments'
